Replaced implicit animation modifiers with explicit animation ('withA…
nickffox/KeyboardObserving pull request #13
Opened 2020-03-11 16:44 UTC by omroz

Replaced implicit animation modifiers with explicit animation ('withAnimation'), in order to animate all the affected views returned in the content view, thus preventing non-keyboard animation to stuck.
(Attached sample project)
[KeyboardObservingSample.zip](https://github.com/nickffox/KeyboardObserving/files/4319502/KeyboardObservingSample.zip)

2020-03-12 16:30 UTC, nickffox commented
Thank you for this PR! I’ll do some testing this weekend and get this merged.

2020-03-15 20:44 UTC, nickffox commented
Hey @omroz!

Can you help me understand the problem you're trying to solve this this PR? Based on my testing with Xcode 11.3.1 with an iOS 13.3 simulator, it seems like this change breaks makes views in a `KeyboardObservingView` jump to their destination without any.

| With This Change | Before this Change |
| - | - |
| ![kbo_withAnimation](https://user-images.githubusercontent.com/3590140/76710223-f054cf80-66c2-11ea-9f35-97aed679d0aa.gif) | ![kbo_current](https://user-images.githubusercontent.com/3590140/76710226-f77bdd80-66c2-11ea-9003-7674d73d1b27.gif) |

2020-03-15 22:04 UTC, omroz commented
Hey Nick,

The problem that I had was related to the animation of the “test" button above the keyboard, once I clicked it.
Before the change - the button wouldn't be animated and only the first frame would appear.
After the change - the button was fully animated with scaling effects of 3 white dots.
![Before the Change](https://user-images.githubusercontent.com/42301633/76711292-58350580-6717-11ea-90f6-efe6168f8eff.gif)
![After the Change](https://user-images.githubusercontent.com/42301633/76711298-5d925000-6717-11ea-867c-4726a9b0e7af.gif)
Unfortunately, I missed the part where the keyboard animation would be affected by this change as well.

2020-03-18 09:24 UTC, nickffox requested changes
Marking with Request changes until the keyboard animation issue is resolved.

2020-03-28 21:09 UTC, nickffox commented
@omroz do you plan to address the keyboard animation issue? Otherwise I'm going to close this PR for now.

2020-03-30 01:18 UTC, omroz commented
Currently, I can't find a reasonable solution that could give an answer for both animations (keyboard + content view), therefore I'm closing this PR and I'll upload a new one once I'll figure that out.
Thanks

2020-03-30 01:18 UTC, closed without merging